name: build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install flet
          pip install requests lxml

      - name: Build APK with Flet
        run: flet build apk --include-packages requests lxml

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-apk
          path: build/apk/*.apk
