name: build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install flet and dependencies (for build)
        run: |
          pip install --upgrade flet
          # 虽然 flet build 会自己处理 requirements.txt，但预装一下也没坏处
          pip install requests lxml

      - name: Build APK with Flet
        run: flet build apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-apk
          path: build/apk/*.apk
